services:
  postgres:
    image: 'postgres:17'
    environment:
      - 'POSTGRES_DB=url-shortener'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'